<?php
$pageTitle       = 'Privacy Policy - PolyForge';
$pageDescription = 'PolyForge privacy policy — what data we collect (none) and how your privacy is protected.';
$pageSlug        = 'privacy';
require __DIR__ . '/partials/header.php';
?>

  <main id="main">
    <div class="container prose">
      <h1>Privacy Policy</h1>
      <p class="effective-date">Effective date: March 2025</p>

      <p>This Privacy Policy describes how PolyForge ("we", "us", "the project") handles information when you use the PolyForge desktop application and website.</p>

      <h2>1. Information we collect</h2>
      <p>PolyForge does not collect, store, or transmit any personal information. The application runs entirely on your local machine.</p>
      <ul>
        <li><strong>No telemetry:</strong> PolyForge does not send usage data, crash reports, or analytics to any server.</li>
        <li><strong>No personal data:</strong> We do not collect names, email addresses, IP addresses, or any personally identifiable information through the application.</li>
        <li><strong>No tracking:</strong> We do not use cookies, tracking pixels, or similar technologies in the application.</li>
      </ul>

      <h2>2. Website</h2>
      <p>The PolyForge website is hosted on shared hosting with Cloudflare. Standard web server logs may be generated by the hosting provider and Cloudflare, which may include IP addresses, browser type, and access timestamps. These logs are managed by the hosting infrastructure and are not used by the PolyForge project for any purpose.</p>

      <h2>3. Third-party services</h2>
      <p>The website loads fonts from Google Fonts. Google's privacy policy applies to that service. No other third-party analytics, advertising, or tracking services are used on the PolyForge website.</p>

      <h2>4. Network activity</h2>
      <p>The PolyForge application makes network requests only to download modpack files from their source locations (e.g., Modrinth, CurseForge) during the install process. No data about you or your system is transmitted.</p>

      <h2>5. Data storage</h2>
      <p>All data created by PolyForge (installed modpacks, configurations, logs) is stored locally on your machine. PolyForge does not use cloud storage, remote databases, or external servers for user data.</p>

      <h2>6. Children's privacy</h2>
      <p>PolyForge does not knowingly collect any information from anyone, including children under the age of 13. Since no personal data is collected, no special provisions are required.</p>

      <h2>7. Changes to this policy</h2>
      <p>If this privacy policy is updated, the changes will be reflected on this page with an updated effective date. Since PolyForge does not collect contact information, we cannot notify users directly — please check this page periodically.</p>

      <h2>8. Contact</h2>
      <p>If you have questions about this privacy policy, you can reach out via the <a href="https://github.com/realKeehan/PolyForge" target="_blank" rel="noopener noreferrer">PolyForge GitHub repository</a>.</p>
    </div>
  </main>

<?php require __DIR__ . '/partials/footer.php'; ?>
